In [1]:
import pandas as pd

In [7]:
reviews = pd.read_csv('../dataset/reviews_onkel.csv')

In [8]:
reviews.head()

               nama                                             review
0            ekov_3  Awalnya penasaran deket hotel kuk ramai sekali...
1        Siba Waihi  Kopi & snack nya enak, tersedia makanan berat,...
2    Alvia Fadliana  Tempatnya sangat nyaman, tenang, relax.\nsy or...
3  aisah ulfah Syam  Temptnya bagus makanan enak & ada live musikny...
4   Muhammad Ikhsan  Saya pesan mie kuah tom yam, enak dan segar. T...

In [11]:
reviews.shape

(194, 2)

In [16]:
reviews['review'].isna().sum()

np.int64(66)

In [14]:
reviews.shape[0] - reviews['review'].isna().sum()

np.int64(128)

In [18]:
reviews.dropna(inplace=True)

In [20]:
reviews.shape

(128, 2)

In [21]:
reviews

                    nama                                             review
0                 ekov_3  Awalnya penasaran deket hotel kuk ramai sekali...
1             Siba Waihi  Kopi & snack nya enak, tersedia makanan berat,...
2         Alvia Fadliana  Tempatnya sangat nyaman, tenang, relax.\nsy or...
3       aisah ulfah Syam  Temptnya bagus makanan enak & ada live musikny...
4        Muhammad Ikhsan  Saya pesan mie kuah tom yam, enak dan segar. T...
..                   ...                                                ...
124        Jilian Savary  Superb cafe in the city center. Great atmosphe...
125  Anwar Jimpe Rachman  Those who smoke and can do it indoors, this pl...
126    Elisabeth Dessaux  A warm and welcoming place, like a second home...
133             Sui Yeng                                          Perfect!!
135            Juan Nita                                             Forget

[128 rows x 2 columns]

In [22]:
reviews.to_csv("../dataset/reviews_onkel_clean",index=False)