In [1]:
import re
import string

import pandas as pd

In [2]:
reviews_cust = pd.read_csv('../dataset/reviews_Onkel John\'s Coffee Hasanuddin.csv')

In [3]:
reviews_cust.head()

,nama,reviews,rating
0,ekov_3,Awalnya penasaran deket hotel kuk ramai sekali...,5 bintang
1,Siba Waihi,"Kopi & snack nya enak, tersedia makanan berat,...",5 bintang
2,Alvia Fadliana,"Tempatnya sangat nyaman, tenang, relax.\nsy or...",5 bintang
3,Jasmir Aly,Sangat rekomended.\nDan pelayanannya sangat ba...,5 bintang
4,aisah ulfah Syam,Temptnya bagus makanan enak & ada live musikny...,5 bintang

Preprocess Reviews

In [4]:
reviews_cust.isna().sum()

nama        0
reviews    80
rating      0
dtype: int64

In [5]:
reviews_cust[reviews_cust['reviews'].isna()]

                nama reviews     rating
118        A M F G M     NaN  4 bintang
151  PIERE PINONTOAN     NaN  5 bintang
152  Adha priyatnadi     NaN  5 bintang
154     Ahya Ahmadan     NaN  5 bintang
155    Kiki Sumarlin     NaN  5 bintang
..               ...     ...        ...
234     Suzy Kandani     NaN  3 bintang
235  Fida Sulystiani     NaN  5 bintang
236    ffajrin karim     NaN  5 bintang
237       haris bayu     NaN  5 bintang
238      erisoya Jrm     NaN  5 bintang

[80 rows x 3 columns]

In [6]:
reviews_cust.dropna(inplace=True)

In [7]:
reviews_cust['rating'] = reviews_cust['rating'].apply(lambda x: int(re.search(r"(\d+)", x).group()))

In [8]:
reviews_cust.info()

<class 'pandas.core.frame.DataFrame'>
Index: 159 entries, 0 to 176
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nama     159 non-null    object
 1   reviews  159 non-null    object
 2   rating   159 non-null    int64
dtypes: int64(1), object(2)
memory usage: 5.0+ KB

In [9]:
reviews_cust[reviews_cust['rating'] < 4]

,nama,reviews,rating
9,FX Martin,secara umum tempatnya enak utk ngobrol dan ngo...,3
30,Havid Han,Tempat yang menyenangkan untuk hang out. Kopin...,3
31,Ferdi choco,Pelayanan perlu di tingkatkan lagi jangan cuma...,3
37,salma sisil,"baristanya sebagian mukanya jutek, mmg pribumi...",1
39,Ferdi choco,Pelayanan perlu di tingkatkan lagi jangan cuma...,3
58,eric tsu,"Roti kaya isiannya sedikit banget, tipis tipis...",2
62,Muh Alif,Pelayanan lama sekalai. Ampun ini tempat. Tida...,1
91,Ukka 46,Tidal usah ada tukang parkir. Pemgeluaran tamb...,1
99,Herman Daeng Sijaya,Sangat tdk menyenangkan perilaku anggota manag...,1
127,Pierre Martin,"Tempatnya bagus, makanan dan kopinya enak, tap...",3

In [10]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [11]:
def clean_text(text: str):
    text = text.lower()
    
    # punctuation
    text = re.sub(r'[^a-zA-Z0-9]', ' ', text)

    # remove digit
    text = ''.join(char for char in text if not char.isdigit())

    text = ' '.join(text.split())

    return text

reviews_cust['cleaned_reviews'] = reviews_cust['reviews'].apply(lambda x: clean_text(x))

In [12]:
reviews_cust

,nama,reviews,rating,cleaned_reviews
0,ekov_3,Awalnya penasaran deket hotel kuk ramai sekali...,5,awalnya penasaran deket hotel kuk ramai sekali...
1,Siba Waihi,"Kopi & snack nya enak, tersedia makanan berat,...",5,kopi snack nya enak tersedia makanan berat par...
2,Alvia Fadliana,"Tempatnya sangat nyaman, tenang, relax.\nsy or...",5,tempatnya sangat nyaman tenang relax sy order ...
3,Jasmir Aly,Sangat rekomended.\nDan pelayanannya sangat ba...,5,sangat rekomended dan pelayanannya sangat bagu...
4,aisah ulfah Syam,Temptnya bagus makanan enak & ada live musikny...,5,temptnya bagus makanan enak ada live musiknya ...
...,...,...,...,...
164,Juan Nita,Lupa,5,lupa
165,Ibnu 5061,Ada musik live👍,5,ada musik live
167,Alit CeKa,Tempat yang nyaman..,5,tempat yang nyaman
174,Ina Rusli,Pelayanannya sempurna!! 👍🏻 …,5,pelayanannya sempurna
176,Ina Rusli,Pelayanannya sempurna!! 👍🏻,5,pelayanannya sempurna

In [20]:
reviews_cust['tokens'] = reviews_cust['cleaned_reviews'].apply(lambda x: x.split())

In [24]:
reviews_cust

,nama,reviews,rating,cleaned_reviews,tokens
0,ekov_3,Awalnya penasaran deket hotel kuk ramai sekali...,5,awalnya penasaran deket hotel kuk ramai sekali...,"[awalnya, penasaran, deket, hotel, kuk, ramai,..."
1,Siba Waihi,"Kopi & snack nya enak, tersedia makanan berat,...",5,kopi snack nya enak tersedia makanan berat par...,"[kopi, snack, nya, enak, tersedia, makanan, be..."
2,Alvia Fadliana,"Tempatnya sangat nyaman, tenang, relax.\nsy or...",5,tempatnya sangat nyaman tenang relax sy order ...,"[tempatnya, sangat, nyaman, tenang, relax, sy,..."
3,Jasmir Aly,Sangat rekomended.\nDan pelayanannya sangat ba...,5,sangat rekomended dan pelayanannya sangat bagu...,"[sangat, rekomended, dan, pelayanannya, sangat..."
4,aisah ulfah Syam,Temptnya bagus makanan enak & ada live musikny...,5,temptnya bagus makanan enak ada live musiknya ...,"[temptnya, bagus, makanan, enak, ada, live, mu..."
...,...,...,...,...,...
164,Juan Nita,Lupa,5,lupa,[lupa]
165,Ibnu 5061,Ada musik live👍,5,ada musik live,"[ada, musik, live]"
167,Alit CeKa,Tempat yang nyaman..,5,tempat yang nyaman,"[tempat, yang, nyaman]"
174,Ina Rusli,Pelayanannya sempurna!! 👍🏻 …,5,pelayanannya sempurna,"[pelayanannya, sempurna]"
176,Ina Rusli,Pelayanannya sempurna!! 👍🏻,5,pelayanannya sempurna,"[pelayanannya, sempurna]"

In [ ]:
import nltk
from nltk.corpus import stopwords

stop_words_indonesia = set(stopwords.words('indonesian'))

def lemmatize_tokens(tokens):
    return " ".join([lemmatize_tokens])